#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/wxdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    #password: runasone
#    driver-class-name: com.mysql.cj.jdbc.Driver

